### ISSUE TITLE
Notification popup displays on fresh installation when should be off by default

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [Strappazzon/GRW-GHOST-Buster#1]
### Describe the bug
The popup notification displays even though its supposed to be off by default (on a fresh installation). Toggling its settings tick box makes no difference. I went back to this great little util after getting a smart gaming TV. I think the bug must have been there many months ago when I was last using the util as I can remember notifications coming up. However on the new TV the popups makes the game lost focus and this causes all sorts of resolution problems. Previously I must have been running borderless but have to run in fullscreen on the new display.

### Reproduction steps
Fresh install. Load game. Popup appears.

### Expected behavior
Popup should be off by default.

### Platform

- **OS:** Windows 10 latest.
- **GHOST Buster Version:** Latest.

### Additional information
Thanks for the util !

**Comment by Strappazzon** [comment]
Thanks for reporting the issue! This is fixed in GHOST Buster 2.0.1.

---

> the popups makes the game lost focus and this causes all sorts of resolution problems. Previously I must have been running borderless but have to run in fullscreen on the new display.

Yes unfortunately the notification will make the game switch from exclusive fullscreen to borderless fullscreen.
